### ISSUE TITLE
Why a dependancy to ext-posix?

### ISSUE THREAD

**Issue by zarunet** [webparking/laravel-type-safe-collection#1]
https://github.com/webparking/laravel-type-safe-collection/blob/25e9a2883c3d69de100ad07405ee571c6e695c94/composer.json#L32

As far as i can tell, none of the posix functions are used in this package, so why making it a dependancy?

(context: my company recently switched from a linux-based dev environment to a windows-based environment, and this dependancy is preventing me to install other, completely unrelated, composer packages in my project)

**Comment by remkobrenters** [comment]
Hmm that could be a typo indeed. We will look into and get back to you.

**Comment by zarunet** [comment]
Thanks! In the meantime, adding `--ignore-platform-reqs ext-posix` to my composer commands allowed me to bypass the issue temporarily.

Edit: this DID add `"ext-posix": "*"` in my own composer.json, so maybe that's how it got there in the first place?

**Comment by remkobrenters** [comment]
Hereby removed the posix requirement. Happy coding and thanks for helping us making this repo better.
